[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiogram>=3.21.0",
    "openpyxl>=3.1.5",
    "reportlab>=4.4.3",
]
